spring:
  application:
    name: desafio-sistema-de-reserva-de-restaurante
  datasource:
    url: jdbc:mysql://localhost:3306/desafio-sistema-de-reserva-de-restaurante?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    open-in-view: false